import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="pt-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <div className="container">
          <h1 className="text-center">Native {`<img>`} tag usage</h1>
          <h5 className="text-center pt-5">Example of a background image, taking 100% of its parent width</h5>
        </div>
        {/* The following div is outside a container so it takes the full view port width */}
        <div className="pt-2">
          <img src="/assets/images/unsplash-1.jpeg" style={{width: "100%", height: "auto"}}/>
        </div>

        <div className="container pb-5">
          <h5 className="text-center  pt-5 pb-2">Example of a card image</h5>
          <div className="card" style={{width: "18rem"}}>
            <img src="/assets/images/unsplash-1.jpeg" class="card-img-top" alt="..." />
            <div className="card-body">
              <h5 className="card-title">Card title</h5>
              <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
        </div>

       <div className="container">
          <h1 className="text-center pt-5 pb-2">Next.js {`<Image>`} component usage</h1>
          <h5 className="text-center pt-5">Example of a background image, taking 100% of its parent width</h5>
        </div>
        {/* The following div is outside a container so it takes the full view port width */}
        {/* the heigth: 66.58vw was calculated in order to match the image unsplash-1.jpeg aspect ratio of 1.5*/}
          <div className="pt-2" style={{  position: 'relative', width: '100vw', height: '66.66vw'}}>
            <Image 
            src="/assets/images/unsplash-1.jpeg"
            layout="fill"
            objectFit="cover"
            />
          </div>

          <div className="container">
            <h5 className="text-center  pt-5 pb-2">Example of a card image</h5>
            <div className="card" style={{width: "18rem"}}>
              <Image 
              src="/assets/images/unsplash-1.jpeg"
              // just put the original width and height of the original image, in order to provide the right aspect ratio
              // Next.js will automatically reduce the size if the rendered image needs to be smaller.
              width={2400}
              height={1598}
              layout="responsive"
              class="card-img-top" alt="..." />
              <div className="card-body">
                <h5 className="card-title">Card title</h5>
                <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>

      </main>
        
    </div>
  )
}
